### ISSUE TITLE
log files after the errors of #7 contain a nonprintable character, fooling up encoding

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_next_generation#8]
As seen in emacs:
```
...
10:18:50.049 [Err] [camera-1]                             Obj.sendProbingResult(outgoing); - Failed to send (on POSIX socket '\0lipp-unit-camera-1-probing') data='{"AnswersToProbe":false}'
...
```
As seen in gedit instead
```
㙛㘸㈷崷㈠㈰ⴴ㄰㈭″㠰ㄺ㨷〴㜮㤵㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊㠶㜶㜲⁝〲㐲〭ⴱ㌲〠㨸㜱㐺⸰㤸‱‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㙛㘸㈷崷㈠㈰ⴴ㄰㈭″㠰ㄺ㨷〴㤮ㄱ㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㘽㘸㈷崷氠灩⵰牤癩牥挭浡牥ⵡ㨱ⴠⴭ‭瑓牡整⁤ⴭⴭ嬊㠶㜶㜲⁝〲㐲〭ⴱ㌲〠㨸㜱㐺⸰㜹‵‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤㠶㜶㜲⁝楬灰搭楲敶⵲慣敭慲ㄭ›牣慥整⁤佐䥓⁘潳正瑥瀠瑡㵨氧灩⵰牤癩牥挭浡牥ⵡ✱‬楴敭畯㵴ਵ㙛㘸㈷崷㈠㈰ⴴ㄰㈭″㠰ㄺ㨷ㄴ〮㔲㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㘽㘸㈷崷氠灩⵰牤癩牥挭浡牥ⵡ㨱䌠污楬杮漠獢愮楰洮歡䅥楰✨潌慣楴湯Ⱗ✠嬊㠶㜶㜲⁝〲㐲〭ⴱ㌲〠㨸㜱㐺⸱㔴″‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㙛㘸㈷崷㈠㈰ⴴ㄰㈭″㠰ㄺ㨷ㄴ㘮㈴㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊㠶㜶㜲⁝〲㐲〭ⴱ㌲〠㨸㜱㐺⸲㔰‰‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㙛㘸㈷崷㈠㈰ⴴ㄰㈭″㠰ㄺ㨷㌴㔮㈳㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㘽㘸㈷崷氠灩⵰牤癩牥挭浡牥ⵡ㨱传ⱋ朠瑯愠✠扯⹳灡⹩牷灡数獲挮浡牥❡映牯愠✠湩瑳儮奈捣❤漠橢捥ੴ㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳㌰〮㘵㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱〺⸳㤱‶‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳㌰㈮㠱㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㜽㜸㈹崶氠灩⵰牤癩牥挭浡牥ⵡ㨱ⴠⴭ‭瑓牡整⁤ⴭⴭ嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱〺⸳㠲‴‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤㠷㤷㘲⁝楬灰搭楲敶⵲慣敭慲ㄭ›牣慥整⁤佐䥓⁘潳正瑥瀠瑡㵨氧灩⵰牤癩牥挭浡牥ⵡ✱‬楴敭畯㵴ਵ㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳㌰㐮㤴㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㜽㜸㈹崶氠灩⵰牤癩牥挭浡牥ⵡ㨱䌠污楬杮漠獢愮楰洮歡䅥楰✨潌慣楴湯Ⱗ✠嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱〺⸳㐷″‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳㌰㤮㜴㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱〺⸴㐳‹‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳㔰㠮㔲㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㜽㜸㈹崶氠灩⵰牤癩牥挭浡牥ⵡ㨱传ⱋ朠瑯愠✠扯⹳灡⹩牷灡数獲挮浡牥❡映牯愠✠湩瑳儮奈捣❤漠橢捥ੴ㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳㔱㈮㔷㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㜽㜸㈹崶氠灩⵰牤癩牥挭浡牥ⵡ㨱䐠楲敶⁲氧灩⵰牤癩牥挭浡牥ⵡ✱椠⁳搧瑥捥整❤嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱㈺⸰㈴‶‾孛剅嵒崠䔠捸灥楴湯›䅍䱔䉁椺摮硥攺灸捥整彤湯彥畯灴瑵晟潲彭硥牰獥楳湯ⴠ䔠灸捥整⁤湯⁥畯灴瑵映潲⁭⁡畣汲⁹牢捡⁥牯搠瑯椠摮硥湩⁧硥牰獥楳湯‬畢⁴桴牥⁥敷敲〠爠獥汵獴‮‭硅数瑣摥漠敮漠瑵異⁴牦浯愠挠牵祬戠慲散漠⁲潤⁴湩敤楸杮攠灸敲獳潩Ɱ戠瑵琠敨敲眠牥⁥‰敲畳瑬⹳《㨹㌱㈺⸰㈳‴䕛牲⁝捛浡牥ⵡ崱䔠牲牯椠⁮扯⹳灡⹩佐䥓獘捯敫⹴祰佐䥓獘捯敫⽴敳摮潴⠠楬敮㐠⤵《㨹㌱㈺⸰㈳‴䕛牲⁝捛浡牥ⵡ崱††††††戠瑹獥㴠漠橢献捯敫⹴⹳敳摮潴洨杳琬牡敧側瑡⥨਻㤰ㄺ㨳〲㌮㐲嬠牅嵲嬠慣敭慲ㄭ⁝牅潲⁲湩漠獢愮楰䰮灩⽰敳摮牐扯湩剧獥汵⁴氨湩⁥㌲⤴《㨹㌱㈺⸰㈳‴䕛牲⁝捛浡牥ⵡ崱††††††††传橢倮潲楢杮潓正瑥献湥瑤⡯扏⹪牐扯湩卧捯敫側瑡ⱨ搠瑡⥡਻㤰ㄺ㨳〲㌮㐲嬠牅嵲嬠慣敭慲ㄭ⁝牅潲⁲湩漠獢愮楰䰮灩⽰潬灯⠠楬敮㈠㌶਩㤰ㄺ㨳〲㌮㐲嬠牅嵲嬠慣敭慲ㄭ⁝††††††††††††††扏⹪敳摮牐扯湩剧獥汵⡴畯杴楯杮㬩ⴠ䘠楡敬⁤潴猠湥⁤漨⁮佐䥓⁘潳正瑥✠氀灩⵰湵瑩挭浡牥ⵡⴱ牰扯湩❧ 慤慴✽≻湁睳牥味偯潲敢㨢慦獬絥‧嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱㈺⸰㌴′‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤㠷㤷㘲⁝楬灰搭楲敶⵲慣敭慲ㄭ›慢汩畏㩴洠杳✽敳摮牐扯湩剧獥汵❴嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱㈺⸰㌴‶‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤㠷㤷㘲⁝楬灰搭楲敶⵲慣敭慲ㄭ›慢汩畏㩴†牦浯䰠灩⹰㩭㌲‷楌灰献湥偤潲楢杮敒畳瑬嬊㠷㤷㘲⁝〲㐲〭ⴱ㌲〠㨹㌱㈺⸰㐴‰‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤㠷㤷㘲⁝楬灰搭楲敶⵲慣敭慲ㄭ›慢汩畏㩴†牦浯䰠灩⹰㩭㘲″楌灰氮潯ੰ㝛㜸㈹崶㈠㈰ⴴ㄰㈭″㤰ㄺ㨳〲㐮㐴㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㜽㜸㈹崶氠灩⵰牤癩牥挭浡牥ⵡ㨱戠楡佬瑵›㰼‼楰㩤㜠㜸㈹ⰶ⠠硥瑩湩⁧楷桴爠㵣⤱†㸾ਾ嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㌺⸲㈷‷‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸㈳㠮㠶㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㌺⸲㤸‱‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤ㄹㄳ㤴⁝楬灰搭楲敶⵲慣敭慲ㄭ›ⴭⴭ匠慴瑲摥ⴠⴭਭ㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸㈳㤮㐵㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㤽㌱㐱崹氠灩⵰牤癩牥挭浡牥ⵡ㨱挠敲瑡摥倠协塉猠捯敫⁴慰桴✽楬灰搭楲敶⵲慣敭慲ㄭⰧ琠浩潥瑵㔽嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㌺⸳㌱‴‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤ㄹㄳ㤴⁝楬灰搭楲敶⵲慣敭慲ㄭ›慃汬湩⁧扯⹳灡⹩慭敫灁⡩䰧捯瑡潩❮‬ਧ㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸㌳㐮〴㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㌺⸳㌶‵‾㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽‽瑓牡整੤㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸㐳〮㜴㸠㴠㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽㴽匠慴瑲摥嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㌺⸵㐵‰‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤ㄹㄳ㤴⁝楬灰搭楲敶⵲慣敭慲ㄭ›䭏‬潧⁴⁡漧獢愮楰眮慲灰牥⹳慣敭慲‧潦⁲⁡椧獮⹴䡑捙摣‧扯敪瑣嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㐺⸴㤹‷‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤ㄹㄳ㤴⁝楬灰搭楲敶⵲慣敭慲ㄭ›牄癩牥✠楬灰搭楲敶⵲慣敭慲ㄭ‧獩✠敤整瑣摥ਧ㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸〵ㄮ㔵㸠嬠䕛剒⁝⁝硅散瑰潩㩮䴠呁䅌㩂湩敤㩸硥数瑣摥潟敮潟瑵異彴牦浯敟灸敲獳潩⁮‭硅数瑣摥漠敮漠瑵異⁴牦浯愠挠牵祬戠慲散漠⁲潤⁴湩敤楸杮攠灸敲獳潩Ɱ戠瑵琠敨敲眠牥⁥‰敲畳瑬⹳ⴠ䔠灸捥整⁤湯⁥畯灴瑵映潲⁭⁡畣汲⁹牢捡⁥牯搠瑯椠摮硥湩⁧硥牰獥楳湯‬畢⁴桴牥⁥敷敲〠爠獥汵獴ਮ〱ㄺ㨸〵〮㤴嬠牅嵲嬠慣敭慲ㄭ⁝牅潲⁲湩漠獢愮楰倮协塉潳正瑥瀮偹协塉潳正瑥猯湥瑤⁯氨湩⁥㔴਩〱ㄺ㨸〵〮㤴嬠牅嵲嬠慣敭慲ㄭ⁝††††††祢整⁳‽扯⹪潳正瑥献献湥瑤⡯獭Ⱨ慴杲瑥慐桴㬩ㄊ㨰㠱㔺⸰㐰‹䕛牲⁝捛浡牥ⵡ崱䔠牲牯椠⁮扯⹳灡⹩楌灰猯湥偤潲楢杮敒畳瑬⠠楬敮㈠㐳਩〱ㄺ㨸〵〮㤴嬠牅嵲嬠慣敭慲ㄭ⁝††††††††扏⹪牐扯湩卧捯敫⹴敳摮潴伨橢倮潲楢杮潓正瑥慐桴‬慤慴㬩ㄊ㨰㠱㔺⸰㐰‹䕛牲⁝捛浡牥ⵡ崱䔠牲牯椠⁮扯⹳灡⹩楌灰氯潯⁰氨湩⁥㘲⤳ㄊ㨰㠱㔺⸰㐰‹䕛牲⁝捛浡牥ⵡ崱††††††††††††††传橢献湥偤潲楢杮敒畳瑬漨瑵潧湩⥧※‭慆汩摥琠⁯敳摮⠠湯倠协塉猠捯敫⁴'楬灰甭楮⵴慣敭慲ㄭ瀭潲楢杮⤧搠瑡㵡笧䄢獮敷獲潔牐扯≥昺污敳❽ਠ㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸〵ㄮ㈶㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㤽㌱㐱崹氠灩⵰牤癩牥挭浡牥ⵡ㨱戠楡佬瑵›獭㵧猧湥偤潲楢杮敒畳瑬ਧ㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸〵ㄮ㜶㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㤽㌱㐱崹氠灩⵰牤癩牥挭浡牥ⵡ㨱戠楡佬瑵›映潲⁭楌灰洮㈺㜳䰠灩⹰敳摮牐扯湩剧獥汵ੴ㥛㌱㐱崹㈠㈰ⴴ㄰㈭″〱ㄺ㨸〵ㄮ㈷㸠嬠义嵆嬠慣敭慲ㄭ⁝灛摩㤽㌱㐱崹氠灩⵰牤癩牥挭浡牥ⵡ㨱戠楡佬瑵›映潲⁭楌灰洮㈺㌶䰠灩⹰潬灯嬊ㄹㄳ㤴⁝〲㐲〭ⴱ㌲ㄠ㨰㠱㔺⸰㜱‶‾䥛䙎⁝捛浡牥ⵡ崱嬠楰㵤ㄹㄳ㤴⁝楬灰搭楲敶⵲慣敭慲ㄭ›慢汩畏㩴㰠㰼瀠摩›ㄹㄳ㤴‬攨楸楴杮眠瑩⁨捲ㄽ 㸠㸾ਊ
```

**Comment by EastEriq** [comment]
Also null char in `'b'\x00lipp-driver-camera-1'` in messages like
```
2024-01-23 10:57:31,075 - INFO     - {lipp-unit-camera-1:receive_from_driver:977143:camera-1-wait-for-ready-thread:140660494669568} -  got 'b'{"RequestId":0,"Value":"detected"}'' from 'b'\x00lipp-driver-camera-1'
``

**Comment by EastEriq** [comment]
Now I recall that there is this convention of heading null char on unix sockets. That should be removed though when printing out the socket name in messages....

**Comment by blumzi** [comment]
Fixed, no log of null chars

**Comment by EastEriq** [comment]
I still see:
```
13:42:04.905 [Err] [mount-11]                             Obj.sendProbingResult(outgoing); - Failed to send (on POSIX socket '\0lipp-unit-mount-probing') data='{"AnswersToProbe":false}, bytes_sent=-1' 
```
and the like in today's logs. Or was the fix not committed & pulled on last11e?

**Comment by blumzi** [comment]
I missed another place to be fixed.

Need to pull.
